import assert from "node:assert/strict";
import { access, readFile, readdir } from "node:fs/promises";
import test from "node:test";

test("production bundle contains the finished Chinese product", async () => {
  const assetsUrl = new URL("../dist/client/assets/", import.meta.url);
  const files = await readdir(assetsUrl);
  const appBundle = files.find((file) => file.startsWith("AStockApp-") && file.endsWith(".js"));
  assert.ok(appBundle, "AStockApp client bundle should exist");
  const javascript = await readFile(new URL(appBundle, assetsUrl), "utf8");
  assert.match(javascript, /Aria 监盘/);
  assert.match(javascript, /真实指数已更新/);
  assert.match(javascript, /真实数据·实验源/);
  assert.match(javascript, /先算清，再开通/);
  assert.match(javascript, /只推异常/);
  assert.match(javascript, /行业、概念和股票都由你选择/);
  assert.match(javascript, /上一交易日全市场复盘/);
  assert.match(javascript, /相对较强概念/);
  assert.match(javascript, /不是单只股票/);
  assert.match(javascript, /选择一天，查看开盘前后变化/);
  assert.match(javascript, /开盘前基准/);
  assert.match(javascript, /没有数据/);
  assert.match(javascript, /已使用云端缓存/);
  assert.match(javascript, /真实行情读取中/);
  assert.match(javascript, /和我有关的三件事/);
  assert.match(javascript, /关闭页面后不会自动监控/);
  assert.match(javascript, /任务开关目前只保存偏好/);
  assert.match(javascript, /市场风险未完整判断/);
  assert.match(javascript, /计划配置（尚未后台运行）/);
  assert.match(javascript, /这些开关目前只保存你的计划/);
  assert.match(javascript, /指数价格事实/);
  assert.match(javascript, /没有真实批次数据/);
  assert.match(javascript, /下次手动复盘会使用新的股票集合和缓存键/);
  assert.doesNotMatch(javascript, /下一项：/);
  assert.doesNotMatch(javascript, /-3\.42%|-9\.54%|-5\.76%/);
  assert.doesNotMatch(javascript, /盘面守望|盘面先锋/);
  assert.doesNotMatch(javascript, /Your site is taking shape|react-loading-skeleton/i);
  await access(new URL("../dist/client/manifest.webmanifest", import.meta.url));
  await access(new URL("../dist/.openai/drizzle/0000_goofy_paladin.sql", import.meta.url));
});

test("mobile layouts cover the required 360, 390 and 430 pixel widths", async () => {
  const css = await readFile(new URL("../app/globals.css", import.meta.url), "utf8");
  assert.match(css, /@media \(max-width: 760px\)/, "430px should use the mobile layout");
  assert.match(css, /@media \(max-width: 390px\)/, "390px and 360px should use the compact layout");
  assert.match(css, /\.sidebar\s*\{\s*display: none;/s);
  assert.match(css, /\.mobile-nav\s*\{[\s\S]*?display: grid;/);
  assert.match(css, /\.mobile-nav button\s*\{[\s\S]*?min-width: 0;/);
  assert.match(css, /\.today-brief-grid\s*\{[\s\S]*?grid-template-columns: repeat\(3, minmax\(0, 1fr\)\);/);
  assert.match(css, /@media \(max-width: 1080px\)[\s\S]*?\.today-brief-grid\s*\{\s*grid-template-columns: 1fr;/);
  assert.match(css, /@media \(max-width: 390px\)[\s\S]*?\.today-brief-card\s*\{\s*padding: 14px;/);
});
